#!/bin/bash
PY_VER=(2.7.15 3.7.1 3.7.2)
RB_VER=(2.3.8 2.4.5 2.6.1)
NODE_VER=(8.15.0 10.15.1 11.9.0)

# Brew updates
brew update
brew upgrade
brew cask upgrade
brew cleanup -s

# Brew diagnostics
brew doctor
brew missing

# Python pip updates
for python in ${PY_VER[@]}; do
  pyenv install --skip-existing $python
  pyenv shell $python
  python -m pip install --upgrade pip
done

# Ruby gem updates
for ruby in ${RB_VER[@]}; do
  rbenv install --skip-existing $ruby
  rbenv shell $ruby
  gem update --system
done

# Node package manager updates
for node in ${NODE_VER[@]}; do
  nvm install $node
  nvm use $node
  nvm install-latest-npm
done